[tool.poetry]
name = "dz-8-part-1"
version = "0.1.0"
description = ""
authors = ["MAX"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mongoengine = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
